version: '3.21'

services:
  api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    container_name: api
    environment:
      - API_PORT=${API_PORT}
    ports:
      - '${API_PORT}:${API_PORT}'
    networks:
      - api-network
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    networks:
      - api-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
networks:
  api-network:
volumes:
  postgres-data:
