version: '3.21'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    container_name: api
    ports:
      - '${API_PORT}:${API_PORT}'
    networks:
      - api-network
    volumes:
      - .:/app
      - /app/node_modules
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    networks:
      - api-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
networks:
  api-network:
volumes:
  postgres-data:
